# Chungoid MCP Configuration

# Logging Settings
# level: DEBUG, INFO, WARNING, ERROR, CRITICAL
# format: text, json
logging:
  level: "INFO"
  format: "text"
  file: "chungoid_mcp_server.log"
  max_bytes: 10485760 # 10 MB
  backup_count: 5

# ChromaDB Settings
# client_type: http, persistent
chromadb:
  client_type: "persistent"
  host: "localhost"
  port: 8000
  persist_path: "./chroma" # Keep for reference, but not used by HttpClient

# Add other configuration sections as needed, e.g.:
# server:
#   host: "127.0.0.1"
#   port: 8888 