###### THIS IS A TEMPLATE CONFIG FILE ######
###### MOVE TO YOURPROJECT/.CHUNGOID/config.yaml ######

# Chungoid Testing Configuration
# Optimized for fast testing with proper configuration structure
# Based on actual SystemConfiguration model analysis

# ============================================================================
# LLM Configuration
# ============================================================================
llm:
  provider: "openai"
  default_model: "gpt-4o-mini-2024-07-18"    # Most cost-effective model
  fallback_model: "gpt-3.5-turbo"
  timeout: 30                                 # Aggressive timeout for speed
  max_retries: 2                             # Minimal retries for speed
  retry_delay: 1.0
  rate_limit_rpm: 60
  max_tokens_per_request: 2000               # Lower token limits for cost
  enable_cost_tracking: true
  monthly_budget_limit: 10.0                 # Low budget for testing

# ============================================================================
# ChromaDB Configuration  
# ============================================================================
chromadb:
  host: "localhost"
  port: 8000
  use_ssl: false
  default_collection_prefix: "test_chungoid"
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  connection_timeout: 15                     # Faster timeouts
  query_timeout: 30
  max_batch_size: 50                         # Smaller batches for speed
  auto_cleanup_enabled: true
  cleanup_retention_days: 1                  # Aggressive cleanup for testing

# ============================================================================
# Project Configuration
# ============================================================================
project:
  name: "testing_project"
  project_type: "cli_tool"
  description: "Testing configuration for fast development cycles"
  auto_detect_dependencies: true
  auto_detect_project_type: true
  enable_smart_caching: true
  exclude_patterns:
    - "__pycache__"
    - "node_modules" 
    - ".git"
    - "*.pyc"
    - "*.log"
    - ".venv"
    - "*.tmp"
  include_hidden_files: false
  max_file_size_mb: 5                        # Smaller file size limit
  analysis_depth: 3                          # Shallow analysis for speed
  enable_content_analysis: true
  preferred_language_models:
    - "gpt-4o-mini-2024-07-18"

# ============================================================================
# Agent Configuration
# ============================================================================
agents:
  default_timeout: 120                       # Faster default timeout
  max_concurrent_agents: 3                   # Lower concurrency for testing
  enable_parallel_execution: true
  max_retries: 2                             # Minimal retries for speed
  retry_exponential_backoff: true
  base_retry_delay: 1.0                      # Faster retry delay
  enable_automatic_checkpoints: true
  checkpoint_frequency: 10                   # Less frequent checkpoints
  enable_state_compression: true
  enable_performance_monitoring: true
  log_agent_outputs: true
  enable_health_checks: true
  
  # Global max iterations override for fast testing
  default_max_iterations: 3                  # Override all stages to max 3 iterations
  
  # Stage-specific iteration limits
  stage_max_iterations:
    product_analysis: 2
    architecture_design: 3
    blueprint_review: 2
    code_generation: 3
    code_debugging: 2
    documentation_generation: 2
    dependency_management: 2
    environment_bootstrap: 1
    requirements_tracing: 2
    automated_refinement_coordination: 3
  
  # Per-agent timeout overrides for faster testing
  agent_timeouts:
    "EnvironmentBootstrapAgent": 60
    "DependencyManagementAgent_v1": 60
    "ProductAnalystAgent_v1": 90
    "ArchitectAgent_v1": 90
    "RequirementsTracerAgent_v1": 60
    "ProactiveRiskAssessorAgent_v1": 60
    "BlueprintReviewerAgent_v1": 60
    "SmartCodeGeneratorAgent_v1": 120
    "ProjectDocumentationAgent_v1": 60
    "CodeDebuggingAgent_v1": 90
    "AutomatedRefinementCoordinatorAgent_v1": 90
  
  # Per-agent retry limits for faster testing
  agent_retry_limits:
    "EnvironmentBootstrapAgent": 1
    "DependencyManagementAgent_v1": 1
    "ProductAnalystAgent_v1": 2
    "ArchitectAgent_v1": 2
    "RequirementsTracerAgent_v1": 1
    "ProactiveRiskAssessorAgent_v1": 1
    "BlueprintReviewerAgent_v1": 1
    "SmartCodeGeneratorAgent_v1": 2
    "ProjectDocumentationAgent_v1": 1
    "CodeDebuggingAgent_v1": 2
    "AutomatedRefinementCoordinatorAgent_v1": 2

# ============================================================================
# Logging Configuration
# ============================================================================
logging:
  level: "INFO"
  enable_file_logging: true
  log_directory: "logs"
  enable_structured_logging: true
  include_timestamps: true
  include_caller_info: false
  max_log_size_mb: 50                        # Smaller log files
  log_retention_days: 3                      # Shorter retention for testing
  compress_old_logs: true
  mask_secrets: true
  log_api_requests: false                    # Disable for speed
  enable_debug_logging: false                # Disable debug for speed

# ============================================================================
# System Configuration
# ============================================================================
config_version: "1.0.0"
environment: "testing"
enable_telemetry: false                      # Disable for testing
data_directory: "~/.chungoid"

# ============================================================================
# Testing Profile Summary
# ============================================================================
# 
# This configuration is optimized for:
# - Fast testing with max 3 iterations per agent
# - Quick timeouts and minimal retries
# - Cost-effective model usage
# - Minimal logging and monitoring overhead
# - Shallow project analysis for speed
# 
# Environment Variables Required:
# - OPENAI_API_KEY: Your OpenAI API key
# 
# Usage:
# 1. Copy this file to your project's .chungoid/config.yaml
# 2. Or use globally at ~/.chungoid/config.yaml
# 3. Run: chungoid build --goal-file goal.txt --project-dir .
# 
# Expected Behavior:
# - All agents will stop after max 3 iterations
# - Fast execution with minimal resource usage
# - Quick feedback for testing and development
# 
# Environment Variable Overrides:
# - CHUNGOID_UAEI_MAX_ITER=3 (override max iterations)
# - CHUNGOID_UAEI_MODE=multi_iteration (force multi-iteration)
# - CHUNGOID_LLM_DEFAULT_MODEL=gpt-4o-mini-2024-07-18 (override model)
