name: Embed Core Snapshot

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-and-embed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies (core + test extras)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install chromadb httpx

      - name: Run unit tests
        run: pytest -q

      - name: Embed snapshot to ChromaDB (no-op if secrets absent)
        env:
          MCP_API_KEY: ${{ secrets.MCP_API_KEY }}
          CHROMA_HOST: ${{ secrets.CHROMA_HOST }}
          CHROMA_PORT: ${{ secrets.CHROMA_PORT }}
        run: |
          python dev/scripts/embed_core_snapshot.py

      - name: Upload snapshot log artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: core-snapshot-log
          path: .snapshot_embed.log 