# This workflow is intentionally disabled.
# The active workflow is in the root .github/workflows directory.

name: tests

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install pre-commit
      - name: Run tests with coverage
        run: |
          pytest --cov=utils --cov-report=xml --cov-fail-under=35 --quiet
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml-${{ matrix.python-version }}
          path: coverage.xml 