# This workflow is intentionally disabled.
# The active workflow is in the root .github/workflows directory.
# Any other content in this file was part of an older, conflicting workflow definition.

name: old_tests_disabled

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  old_build_disabled:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'This job is intentionally disabled.' 